### ISSUE TITLE
custom theme not loading

### ISSUE THREAD

**Issue by DovWebmark** [podigee/podigee-podcast-player#41] opened 2018-03-20 07:22 UTC
I am adding a local theme using:
`"options": {
 "theme": {
 "css": "<?php echo get_template_directory_uri()?>/css/podigee.css",
"html": "<?php echo get_template_directory_uri()?>/podigee.html",
 }
 },`
but the player doesn't load, and dev tools shows a call to https://podigee.github.io/podigee-podcast-player/build/themes/[object%20Object]/index.html  that returns 404.
What am I doing wrong?

**Comment by DovWebmark** [comment] 2018-03-25 09:08
<div class="episode-item_wrap">
<script>
window.playerConfiguration = {
"options": {
    "theme": {
      "css": "<?php echo get_template_directory_uri()?>/css/podigee.css",
      "html": "<?php echo get_template_directory_uri()?>/podigee.html",
    }
  },
  "episode": {
    "media": {
    <?php if(get_field('episode_audio_mp3')){ ?>
    "mp3": "<?php the_field('episode_audio_mp3'); ?>",
    <?php } ?>
    <?php if(get_field('episode_audio_m4a')){ ?>
    "m4a": "<?php the_field('episode_audio_m4a'); ?>",
    <?php } ?>
    <?php if(get_field('episode_audio_ogg')){ ?>
    "ogg": "<?php the_field('episode_audio_ogg'); ?>",
    <?php } ?>
    <?php if(get_field('episode_audio_opus')){ ?>
    "opus": "<?php the_field('episode_audio_opus'); ?>",
    <?php } ?>
    },
    "title": "<?php the_field('full_name'); ?>",
    "subtitle": "",

    <?php if(get_field('episode_img_cover')){ ?>
    "coverUrl": "<?php the_field('episode_img_cover'); ?>",
    <?php } ?>

    <?php if(get_field('episode_subtitle')){ ?>
    "subtitle": "<?php the_field('episode_subtitle'); ?>",
    <?php } ?>

    "url": "<?php the_permalink(); ?>",


    <?php if(get_field('episode_chapter_marks')){ ?>
    "chaptermarks": [
    <?php if( have_rows('episode_chapter_marks') ):
$i = 1;
while ( have_rows('episode_chapter_marks') ) : the_row(); ?>

{"start": "<?php the_sub_field('start_time'); ?>", "title": "<?php
the_sub_field('title'); ?>"},

<?php $i++; endwhile; endif; ?>
    ]
    <?php } ?>
  },
}
</script>
<script class="podigee-podcast-player" src="
https://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js"
data-configuration="playerConfiguration"></script>


</div>

**Comment by DovWebmark** [comment] 2018-04-09 12:33
?? Still there?

**Comment by benzimmer** [comment] 2018-04-09 23:25
Sorry. I tried this locally and it works fine for me. Can you please add a `console.log(playerConfiguration)` directly after the configuration and paste me the output from devtools so I can see what actually comes out of the PHP stuff?

**Comment by DovWebmark** [comment] 2018-04-11 12:35
{
  "options": {
    "theme": {
      "css": "
http://cybereason-podcast.local/wp-content/themes/cr_podcast/css/podigee.css
",
      "html": "
http://cybereason-podcast.local/wp-content/themes/cr_podcast/podigee.html"
    }
  },
  "episode": {
    "media": {
      "mp3": "
http://traffic.cast.plus/59e4c8c80ef31c05f84ff541/mlife.podbean.com/mf/play/taxz8v/ML_Se2_Ep_09_V2_Isis.mp3
"
    },
    "title": "Malicious Life, episode 18 - Cyber Terrorism",
    "subtitle": "",
    "coverUrl": "
http://cybereason-podcast.local/wp-content/uploads/2018/02/shutterstock_793693936.jpg
",
    "url": "http://cybereason-podcast.local/episode/episode-18/"
  },
  "parentLocationHash": "",
  "embedCode": "<script class=\"podigee-podcast-player\" src=\"
https://podigee.github.io/podigee-podcast-player/build/javascripts/podigee-podcast-player.js\"
data-configuration=\"playerConfiguration\"></script>"
}

**Comment by DovWebmark** [comment] 2018-04-12 05:57
Sorry, I don't know what you mean. Which of these strings has a line break?

**Comment by benzimmer** [comment] 2018-04-12 12:24
Change

```
"css": "
http://cybereason-podcast.local/wp-content/themes/cr_podcast/css/podigee.css
",
```

to

```
"css": "http://cybereason-podcast.local/wp-content/themes/cr_podcast/css/podigee.css",
```

Same goes for all the other strings.

**Comment by DovWebmark** [comment] 2018-04-12 12:46
I don't have any line breaks. Look at the picture.

**Comment by benzimmer** [comment] 2018-04-12 12:51
There was no picture attached to your message.

**Comment by DovWebmark** [comment] 2018-04-12 13:01
![image](
https://user-images.githubusercontent.com/33315851/38659081-6f873ada-3e30-11e8-8309-5bbbbfcdc36a.png
)

**Comment by benzimmer** [comment] 2018-04-13 14:52
Do you have an example page online I can have a look at?

**Comment by DovWebmark** [comment] 2018-04-18 06:45
No. The page isn't live yet. Here is a picture of the result at present:
![screenshot_2](https://user-images.githubusercontent.com/33315851/38915678-36319f02-42ed-11e8-9299-c238473db48c.png)

**Comment by DovWebmark** [comment] 2018-04-22 06:27
?

**Comment by benzimmer** [comment] 2018-04-24 13:30
Can you paste me the rendered source code of the whole page, so I can perhaps try to reproduce it myself?

**Comment by muthughilli** [comment] 2018-04-24 14:17
[gulp_output.zip](https://github.com/podigee/podigee-podcast-player/files/1943102/gulp_output.zip)

Hi,

For the first time, i have build gitup source code using gulp in my local machine. I got the above output. But when i launch, only the animation is playing but nothing happens. I don't find any console errors too. Please let me know what could be the issue. If possible, please provide me a working built podcast files, so that i can take that as reference..

**Comment by benzimmer** [comment] 2018-04-24 21:15
@muthughilli I will delete your message, as it is not related to this thread at all. Please refer to the [readme](https://github.com/podigee/podigee-podcast-player/blob/master/README.md) on how to use the player.

**Comment by michaeljakob** [comment] 2018-07-05 11:49
Is this plugin still updated (or dead?)? I have the same issue on https://www.alleaktien.de/walt-disney-aktienanalyse-auf-dem-weg-zur-zweiten-netflix/

If I type `console.log(playerConfiguration)`, all the correct option:html/css are shown. However, the styling simply does not work. How can we fix this?

Regards,
Michael

**Comment by benzimmer** [comment] 2018-07-05 13:58
@michaeljakob As you'll probably see in the list of commits it's definitely not dead, but if I do not get enough information to track down a potential bug there is not much I can do unfortunately.

In your case the problem seems to be, that you put the `options` object inside of the `episode` object. If you move it to the top level it should work.

**Comment by michaeljakob** [comment] 2018-07-05 15:10
Hey ben,
thank you -- that did the trick!

I have one more issue now, I'm getting a violation of the "same origin policy":

**_No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cdn.podigee.com' is therefore not allowed access._**

Do you have an idea how we could go about this?

Regards,
Michael

**Comment by benzimmer** [comment] 2018-07-05 15:12
@michaeljakob Can you open another issue with the exact code your using to add the player to the page? Also: For which request the warning actually occurs.

**Comment by benzimmer** [comment] 2018-07-05 15:12
In the meantime, I'll close this one until further information about the initial request is provided.

**Closed by benzimmer** 2018-07-05 15:12 UTC
